### ISSUE TITLE
how to i put my assets image [.png] as iconData

### ISSUE THREAD

**Issue by roiskhoiron** [kimmanwky/Motion-Tab-Bar#1]
![image](https://user-images.githubusercontent.com/28525341/128804211-e8ac76bd-79bc-4aa0-a539-f0185aca6a09.png)

**Comment by kimmanwky** [comment]
Hi @roiskhoiron , I'm afraid the current tab item only support Icons. Image is not supported. The reason being is we need to consider for the tab item toggle on/off sizes, colors and other factors. Icon is the only widget which allow changes in color or size. 

Feel free to tweak it to support images and ask for a pull request if necessary.
