### ISSUE TITLE
Unable to change tab programatically

### ISSUE THREAD

**Issue by 4gmayank** [kimmanwky/Motion-Tab-Bar#4]
Step to reproduce
1. I want to change tab programatically
2. i cant set
activeIcon = icon;
selectedTab = tabLabel;
_fadeFabOutAnimation is not able to control it from outside

**Comment by salleh** [comment]
Yup, this is definitely a desirable feature to be done.

Example use case:

On click on one tab item, we want to push a new view (Navigator.push()) then on returning from that view, we want to return to the previous tab and the bar should properly display the selected tab.

**Comment by anees4ever** [comment]
Hello, please see the pull request #5 . I have fixed the issue...

**Comment by kimmanwky** [comment]
pub package version 0.3.0 released with programmatically tab change.
